### PR TITLE
Support UDA part1

### LINKED ISSUE #114: RGB21 support
We'll need to update this in order to support RGB21 for UDAs in addition to RGB20 for fungible assets.

### PR DESCRIPTION
**Pull request by oacdutra**
**Details**
- [x] RGB Contracts v0.10.2
- [x] Issue
- [x] Import
- [x] Invoice
- [x] Transfer
- [x] Accept
- [x] https://github.com/strict-types/strict-types/pull/10
- [x] Issuer Balance (descriptor-wallet bug)
- [x] Support Media (rgb-wallet bug)

Closes #114

### CODE REVIEW

**Comment by oacdutra** [comment]
Hi @cryptoquick and @josediegorobles,

Now we have support to RGB21 (UDA). I need make some changes in rgb-wallet (I will open a PR in rgb-wallet soon).

BTW, we have two issues yet:

* For some reason, the structs **MediaType** and **MediaRegName** does not working when we try validate the global state of the contract.

* I dont kwon why this error occurs: https://github.com/diba-io/bitmask-core/actions/runs/5020876340/jobs/9002747007#step:9:311

**Review by josediegorobles — APPROVED** [review]
ACK

**Review by cryptoquick — CHANGES_REQUESTED** [review]
So, the error appears to be coming from the changes in the web asset test, so it might be a legitimate error? Bear in mind, this error happens at runtime, not compile time:
Error: invalid type: map, expected a string at line 1 column 68

It might be helpful to build the same test, web_asset, in x86_64 too, maybe?

**Comment by oacdutra** [comment]
> So, the error appears to be coming from the changes in the web asset test, so it might be a legitimate error? Bear in mind, this error happens at runtime, not compile time: Error: invalid type: map, expected a string at line 1 column 68
> 
> It might be helpful to build the same test, web_asset, in x86_64 too, maybe?

Hi guys,

I found this bug.

For some reason, the latest version of rgb smart contract StandardTypes causes `RuntimeError: memory access out of bounds` when compiled in wasm32 target.

I will need more time to check that.

My first strategy will be to create a precompiled form of the standard, because the new version does strict type transpilation in runtime and I think this causes memory overflow.


Issue related: https://github.com/RGB-WG/rgb-wallet/issues/52

**Comment by cryptoquick** [comment]
That sounds awesome if it's doable.

**Comment by oacdutra** [comment]
> That sounds awesome if it's doable.

bug fixed!

**Comment by oacdutra** [comment]
Hi @cryptoquick and @josediegorobles, 

I found the issuer bug:

The wallet descriptor always forces the "change address" derivation to  /1/* , not what we determine in the input (asset: /20/* or udas: /21/*).

I will resolve that tomorrow because I need to make more tests in descriptor-wallet and rgb-wallet "velocity" verification.

**Comment by cryptoquick** [comment]
Good thinking! I look forward to seeing it.

**Comment by oacdutra** [comment]
Guys,

I finished!!

I needed to do a lot of modifications in the dependencies, and I will still this week, send all the PRs for official releases. This is important to avoid custom contract interface implementations.

One thing that worry me are possible breaks of compatibility in the contract interfaces. I intend to open some discussions on RGB-WG about this topic, to plan some work related that!

BTW,  my next steps: #181 and #140

**Comment by cryptoquick** [comment]
Awesome! I think we should just merge this since it's passing tests, do a new release of bitmask-core, see how well that integrates with the latest, and we're good to go from there. What do you think, @josediegorobles ?

**Review by cryptoquick — APPROVED** [review]
ACK

**Review by josediegorobles — APPROVED** [review]
ACK

**Pull request merged**
