### PR TITLE
Changing bitmask-core to adapt to the new v3 manifest

### PR DESCRIPTION
**Pull request by josediegorobles**
Because of the difficoulties of passing messages for get data from local storage, i change bitmask-core to get and return the necessary data so the setting and getting will make all in the javascript part.

### CODE REVIEW

**Comment by cryptoquick** [comment]
Good thinking! I definitely agree, persistence should be left up to the user. In our case, it's either a chrome extension or a web page. In v3, there's the sandbox, which might not be terribly persistent or have other limitations.

BTW, check this out in CI:
https://github.com/diba-io/bitmask-core/runs/5769903437?check_suite_focus=true

**Comment by josediegorobles** [comment]
> Good thinking! I definitely agree, persistence should be left up to the user. In our case, it's either a chrome extension or a web page. In v3, there's the sandbox, which might not be terribly persistent or have other limitations.
> 
> BTW, check this out in CI: https://github.com/diba-io/bitmask-core/runs/5769903437?check_suite_focus=true

Yeah, the tests are failing now, i add some paremeters to the methods and now some of them are returning other types; we must modify the tests for that, i think is better a work of mine because i've been modifying the library.

**Comment by josediegorobles** [comment]
@cryptoquick could you review the tests(and the code)? They are compiling but the wallet don't have any balance so one of the tests is failing.

**Comment by cryptoquick** [comment]
Sounds good, @josediegorobles, will do.

**Review by cryptoquick — APPROVED** [review]
Code looks good, and it passes tests. :+1:

**Pull request merged**
