### PR TITLE
Re-Issue (strict-types 1.3.0)

### PR DESCRIPTION
**Pull request by oacdutra**
**Description**

This PR allows you to create a re-issue operation for contracts issued but not transferred.

This action was taken because of the compatibility break generated in strict-types version 1.3.0

### CODE REVIEW

**Review by josediegorobles — APPROVED** [review]
lGTM

**Review by josediegorobles — APPROVED** [review]

**Comment by oacdutra** [comment]
Guys, I will update this PR with the latest version of the strict-types; I think I will finish today.

**Comment by cryptoquick** [comment]
Awesome! Looking forward to it!

**Review by cryptoquick — APPROVED** [review]
ACK

**Pull request merged**
