### PR TITLE
Refactor: remove contract_id

### LINKED ISSUE #354: save_transfers must work only with nostrkey and consignment
We need to get rid of contract_id in save_transfers, it's not necessary and directs to a bad UI in the extension.

save_transfers must work only with nostrkey and consignment

### PR DESCRIPTION
**Pull request by oacdutra**
Close #354

### CODE REVIEW

**Comment by josediegorobles** [comment]
it's not working to me. I made three transactions and all ok with verify included but then the new assets received are not being there.
Yo can try with this: https://github.com/diba-io/bitmask-extension/pull/416

**Comment by oacdutra** [comment]
> it's not working to me. I made three transactions and all ok with verify included but then the new assets received are not being there. Yo can try with this: [diba-io/bitmask-extension#416](https://github.com/diba-io/bitmask-extension/pull/416)

Hi @josediegorobles, 

I tested the PR and I cannot reproduce the error. I made more than 6 transfers and all works.

**Comment by josediegorobles** [comment]
> > it's not working to me. I made three transactions and all ok with verify included but then the new assets received are not being there. Yo can try with this: [diba-io/bitmask-extension#416](https://github.com/diba-io/bitmask-extension/pull/416)
> 
> Hi @josediegorobles,
> 
> I tested the PR and I cannot reproduce the error. I made more than 6 transfers and all works.

I’m going to try again

**Comment by josediegorobles** [comment]
Not working for me.
Is the receiver: is not doing anything.

**Comment by josediegorobles** [comment]
Ok working with fresh wallets

**Review by josediegorobles — APPROVED** [review]
Tested ACK

**Pull request merged**
