### PR TITLE
Adding swap methods to bitmaskd

### PR DESCRIPTION
**Pull request by josediegorobles**

### CODE REVIEW

**Review by oacdutra — COMMENTED** [review]
Are these methods only used by the market?

Does it make sense for the market to request these endpoints by passing the sk instead of invoking the seed on the endpoint?

**Comment by josediegorobles** [comment]
Ok, I have to do some work more before I have this clear

**Comment by cryptoquick** [comment]
Be sure this is updated from what's in `development`

**Comment by josediegorobles** [comment]
> Be sure this is updated from what's in `development`

I resolved the merge conflicts but anyway I convert the PR to draft because I'm using it only to test the marketplace, when the PR of the marketplace is ready, I will put this PR to RFR, until then is not necessary

**Pull request closed without merging**
