### PR TITLE
Correcting errors

### PR DESCRIPTION
**Pull request by josediegorobles**

### CODE REVIEW

**Comment by cryptoquick** [comment]
This is still a work in progress and I'm still thinking through those areas of code.

**Comment by josediegorobles** [comment]
Ok, really i wanted to use it in a lambda, and I corrected for that

**Comment by cryptoquick** [comment]
Okay, I'll get you a rev that compiles.

**Comment by cryptoquick** [comment]
@josediegorobles Please specify this SHA: `ff3dd5e418d88d7098d6799501db8a3e9b67329e`

**Pull request closed without merging**
