### PR TITLE
Add lightning support

### LINKED ISSUE #8: Testnet Lightning Support
Tracking issue for Lightning support

- [x] #89
- [x] #90
- [x] #91

Mainnet Lightning support to come later.

### PR DESCRIPTION
**Pull request by grunch**
Fix #8

### CODE REVIEW

**Comment by cryptoquick** [comment]
@grunch Here are the changes:
https://github.com/diba-io/bitmask-core/pull/100/commits/9df406422daf4ec62eb0bc61134bdfb18f8e549e

**Review by josediegorobles — COMMENTED** [review]
For what I see the code is OK but I have several errors when I try to test.

With wasm-pack test:


`error[E0432]: unresolved import `crate::util::post_json_auth`
 --> src/operations/lightning.rs:3:17
  |
3 |     util::{get, post_json_auth},
  |                 ^^^^^^^^^^^^^^ no `post_json_auth` in `util`

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:184:10
    |
184 |     let (response, _) = post_json_auth::<Credentials>(&create_url, &None, None).await?;
    |          ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:184:25
    |
184 |     let (response, _) = post_json_auth::<Credentials>(&create_url, &None, None).await?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:194:10
    |
194 |     let (response, _) = post_json_auth(&auth_url, &Some(creds), None).await?;
    |          ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:194:25
    |
194 |     let (response, _) = post_json_auth(&auth_url, &Some(creds), None).await?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:208:10
    |
208 |     let (response, _) = post_json_auth(&url, &Some(req), Some(token)).await?;
    |          ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:208:25
    |
208 |     let (response, _) = post_json_auth(&url, &Some(req), Some(token)).await?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src/operations/lightning.rs:218:25
    |
218 |     let (response, _) = get(&url, Some(token)).await?;
    |                         ^^^ ----  ----------- supplied 2 arguments
    |                         |
    |                         expected 1 argument
    |
note: function defined here
   --> src/util.rs:81:14
    |
81  | pub async fn get(url: &str) -> Result<(String, u16)> {
    |              ^^^ ---------

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src/operations/lightning.rs:228:25
    |
228 |     let (response, _) = get(&url, Some(token)).await?;
    |                         ^^^ ----  ----------- supplied 2 arguments
    |                         |
    |                         expected 1 argument
    |
note: function defined here
   --> src/util.rs:81:14
    |
81  | pub async fn get(url: &str) -> Result<(String, u16)> {
    |              ^^^ ---------

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:241:10
    |
241 |     let (response, _) = post_json_auth(&url, &Some(req), Some(token)).await?;
    |          ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/operations/lightning.rs:241:25
    |
241 |     let (response, _) = post_json_auth(&url, &Some(req), Some(token)).await?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src/operations/lightning.rs:251:25
    |
251 |     let (response, _) = get(&url, Some(token)).await?;
    |                         ^^^ ----  ----------- supplied 2 arguments
    |                         |
    |                         expected 1 argument
    |
note: function defined here
   --> src/util.rs:81:14`

**Comment by cryptoquick** [comment]
@josediegorobles Yes, good point, it would appear the linter is failing due to a wasm-compatible implementation not being available in the wasm linter (which can be run with the command `cargo clippy --target wasm32-unknown-unknown --lib -- -D warnings`. It's not a wasm-pack test, since I gave @grunch the direction that wasm support wasn't a requirement yet for the first iteration. It does need to pass the wasm linter though. And the isomorphic test is a flaky test right now; when it fails on the 0 of 100 coins error, it needs to be retried.

**Review by cryptoquick — APPROVED** [review]
This is terrific work! As long as tests and linters pass, it looks good to me.

**Comment by josediegorobles** [comment]
Ok @cryptoquick I see.
Anyway, is a great work so I approve it.

**Review by josediegorobles — APPROVED** [review]

**Comment by cryptoquick** [comment]
To be clear, I still would like this to pass the wasm linter, @josediegorobles @grunch

**Comment by cryptoquick** [comment]
Passes linters and tests! Merging.

**Pull request merged**
