### PR TITLE
UDA improvements

### LINKED ISSUE #404: UDA Attachment Improvements
We'll need to support three separate media attachment formats for our UDAs:

 - [ ] Consignment Embedded Thumbnail
 - [ ] External SHA-256 Image
 - [ ] High Definition Blake3

### PR DESCRIPTION
**Pull request by oacdutra**
**Description**

This PR intent solve the issue #404 

**Changes**

* Now we have a new method to extract and upload all media information in rgb-proxy (previously, this was done within the issuance method). Parameters:
    * **preview:** Represents the preview/thumbnail of the media. The BMC gets the base64 of the media to embedded in the RGB21 contract.
    * **media:** Represents the sha2 of the media. The BMC download binary and get the sha2 of the media (Compatible to Iris Wallet).
    * **attachments:** Intended for other media information, such as the high-definition hash (in blake3).
* Now the issuing method will only receive media type and digest (aka. hash). 

**TODO**
- [x] Split extract metadata and issue contract
- [x] Issue contract operation receive only media type and digest (hash)
- [x] Upload media after extract metadata (rgb-proxy)
- [x] RGB21 is mint with preview, media and attachments information (the last information is optional).
- [x] Expose method in web.rs
- [x] Change typescript structs

Closes #404

### CODE REVIEW

**Comment by cryptoquick** [comment]
Interesting... You don't think this requires any changes to typescript types? Do we need to do anything different on the client?

**Comment by oacdutra** [comment]
> Interesting... You don't think this requires any changes to typescript types? Do we need to do anything different on the client?

This PR is incomplete. Please, see TODO section.

**Comment by josediegorobles** [comment]
You need to review the lint issues

**Comment by Gigi3d** [comment]
**loving this**

**Comment by josediegorobles** [comment]
LGTM

**Review by josediegorobles — APPROVED** [review]
LGTM

**Pull request merged**
