### PR TITLE
Bump Fee

### LINKED ISSUE #433: Replace By Fee (RBF)
We should support fee bumping in the wallet of a specific transaction to a desired fee rate.

### PR DESCRIPTION
**Pull request by cryptoquick**
Closes #433 

- [x] Rust
- [x] Wasm
- [x] TS
- [x] Tests
- [x] BME

### CODE REVIEW

**Comment by josediegorobles** [comment]
The tests about this keep failing

**Comment by oacdutra** [comment]
I will verify the tests, give me 10 minutes.

**Comment by josediegorobles** [comment]
Thanks!

**Review by josediegorobles — APPROVED** [review]
ACK

**Pull request merged**
