### PR TITLE
Add lightning support with lndHub

### PR DESCRIPTION
**Pull request by grunch**
This is WIP, not ready to merge

### CODE REVIEW

**Comment by cryptoquick** [comment]
You requested a review, but you also said it wasn't ready. If it's not ready, be sure to convert this to a draft. If it is ready, let me know to review.

**Comment by grunch** [comment]
I will create another PR for this

**Comment by cryptoquick** [comment]
Why's that?

**Comment by grunch** [comment]
I made a mistake pushing the code using my development branch, now I created a new branch to do a new PR

**Pull request closed without merging**
