### PR TITLE
Adding get_asset

### PR DESCRIPTION
**Pull request by josediegorobles**
For the lambdas we need a without node_url and descriptor version of the method import_asset

### CODE REVIEW

**Comment by cryptoquick** [comment]
This is just the same code as here, right?

https://github.com/diba-io/bitmask-core/blob/6a080391e8b3c629202d1f662784b9367383a095/src/lib.rs#L242-L268

Keep in mind, importing via contract_id might not be a thing we can support until we have a storage solution, like maybe a modified storm node.

**Comment by josediegorobles** [comment]
> This is just the same code as here, right?
> 
> https://github.com/diba-io/bitmask-core/blob/6a080391e8b3c629202d1f662784b9367383a095/src/lib.rs#L242-L268
> 
> Keep in mind, importing via contract_id might not be a thing we can support until we have a storage solution, like maybe a modified storm node.

Yeah, I'm going to do it other way.

**Comment by cryptoquick** [comment]
Okay, this can be closed, then?

**Comment by josediegorobles** [comment]
> Okay, this can be closed, then?

Yeah I wanted to make sure the method can be called without using bdk, for the lambdas/server.

I made optional the descriptor and that's all.

I will make a PR for transfers doing the same.

**Comment by cryptoquick** [comment]
Okay, I'll close it, then.

**Pull request closed without merging**
